#!/bin/bash
######################################
# This script searches the entire system for immutable files,
# then asks if you would like to remove the immutable flag.
# usage: sudo /immutableChk
# should be ran as root to avoid permission denied errors
######################################

#Command this script is based around
#lsattr -a -R / 2>/dev/null | grep -- "-i-" | grep -v -- "-------------"

lsattr -a -R / 2>/dev/null | grep -- "-i-" | grep -v -- "-------------" | grep -v "supported" > imck.tmp

echo ""
while read -r line; do
	name=$line
	echo "$name"
done < "./imck.tmp"

echo ""
if [ -s './imck.tmp' ] ; then
	echo "Would you like to remove the immutable flag from these files? (Y/n)"
	read YESNO
	if [ $YESNO == "Y" ] ; then
		while read -r line; do 
			name=$(echo $line | cut -d" " -f2)
			echo "Removing flag from" $name
			chattr -i $name
		done < "./imck.tmp"
	fi
else
	echo "No immutable flags found"
fi
rm ./imck.tmp

